version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: universidades-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: universidades
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - universidades-network

  universidades-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: universidades-api
    restart: unless-stopped
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/universidades
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: universidades
    ports:
      - "8080:8080"
    networks:
      - universidades-network

networks:
  universidades-network:
    driver: bridge
