apiVersion: v1
kind: Service
metadata:
  name: universidades-service
  labels:
    app: universidades-microservice
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: universidades-microservice
  sessionAffinity: None
